# Generated by Django 5.0 on 2025-11-15 12:06

import django.db.models.deletion
import django.utils.timezone
import users.models.mixins
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('google_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Google User ID')),
                ('line_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Apple User ID')),
                ('facebook_user_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Apple User ID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('user_type', models.CharField(choices=[('OWNER', 'オーナー'), ('STAFF', 'スタッフ'), ('CUSTOMER', '顧客')], max_length=10, verbose_name='ユーザータイプ')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='プロフィール画像')),
                ('profile_image_url', models.URLField(blank=True, help_text='ソーシャルログインの画像URL', null=True, verbose_name='プロフィール画像URL')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='姓')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフステータス')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='スーパーユーザーステータス')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('is_system_admin', models.BooleanField(default=False, help_text='開発者・運営のみ。Django管理画面にアクセス可能', verbose_name='システム管理者')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='ログイン失敗回数')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name='アカウントロック期限')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='パスワード変更日時')),
                ('auth_provider', models.CharField(choices=[('email', 'メール'), ('google', 'Google'), ('line', 'Line'), ('facebook', 'Facebook')], default='email', max_length=20, verbose_name='認証プロバイダー')),
                ('language', models.CharField(blank=True, choices=[('ja', '日本語'), ('en', 'English')], max_length=10, null=True, verbose_name='言語')),
                ('country', models.CharField(blank=True, choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, null=True, verbose_name='国')),
                ('timezone', models.CharField(blank=True, choices=[('Asia/Tokyo', '日本標準時 (JST)'), ('Australia/Sydney', 'オーストラリア東部標準時 (AEST) - シドニー'), ('Australia/Melbourne', 'オーストラリア東部標準時 (AEST) - メルボルン'), ('Australia/Brisbane', 'オーストラリア東部標準時 (AEST) - ブリスベン'), ('Australia/Perth', 'オーストラリア西部標準時 (AWST) - パース'), ('Australia/Adelaide', 'オーストラリア中部標準時 (ACST) - アデレード')], max_length=50, null=True, verbose_name='タイムゾーン')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email', 'user_type'], name='users_email_e7d39f_idx'), models.Index(fields=['is_active', 'user_type'], name='users_is_acti_e1f8d6_idx')],
            },
            bases=(models.Model, users.models.mixins.SecurityMixin, users.models.mixins.PermissionMixin),
        ),
        migrations.CreateModel(
            name='AustralianTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CASUAL', 'Casual'), ('CONTRACT', 'Contract')], max_length=20, verbose_name='雇用形態')),
                ('taxfile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taxfile Number')),
                ('super_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Super Number')),
                ('latest_tax_withheld', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latest Tax Withheld')),
                ('latest_super_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latest Super Amount')),
                ('ytd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=9, null=True, verbose_name='YTD Tax')),
                ('ytd_super', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=20, null=True, verbose_name='YTD Super')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='last Sync')),
                ('user', models.OneToOneField(limit_choices_to={'country': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='australian_tax_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegistrationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('basic_info', '基本情報'), ('detail', '詳細'), ('done', '完了')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_number', models.CharField(blank=True, help_text='12桁の個人番号', max_length=12, verbose_name='マイナンバー')),
                ('pension_number', models.CharField(blank=True, help_text='例: 1234-567890', max_length=20, verbose_name='基礎年金番号')),
                ('employment_insurance_number', models.CharField(blank=True, max_length=20, verbose_name='雇用保険被保険者番号')),
                ('user', models.OneToOneField(limit_choices_to={'country': 'JP'}, on_delete=django.db.models.deletion.CASCADE, related_name='japanese_tax_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='住所')),
                ('suburb', models.CharField(blank=True, max_length=100, verbose_name='Suburb/市区町村')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='州/都道府県')),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('unemployed_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スタッフプロファイル',
                'verbose_name_plural': 'スタッフプロファイル',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffRegistrationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('basic_info', '基本情報'), ('profile', 'プロフィール'), ('done', '完了')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
