# Generated by Django 5.0 on 2025-11-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timezone',
            new_name='user_timezone',
        ),
    ]
