# Generated by Django 5.0 on 2025-11-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='タイムゾーン'),
        ),
    ]
