# Generated by Django 5.0 on 2025-10-31 19:08

import core.models.mixins
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('user_type', models.CharField(choices=[('OWNER', 'オーナー'), ('STAFF', 'スタッフ'), ('CUSTOMER', '顧客')], max_length=10, verbose_name='ユーザータイプ')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフステータス')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='スーパーユーザーステータス')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='メール認証済み')),
                ('is_system_admin', models.BooleanField(default=False, help_text='開発者・運営のみ。Django管理画面にアクセス可能', verbose_name='システム管理者')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='ログイン失敗回数')),
                ('account_locked_until', models.DateTimeField(blank=True, null=True, verbose_name='アカウントロック期限')),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='パスワード変更日時')),
                ('auth_provider', models.CharField(choices=[('email', 'メール'), ('google', 'Google'), ('apple', 'Apple')], default='email', max_length=20, verbose_name='認証プロバイダー')),
                ('language', models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='ja', max_length=10, verbose_name='言語')),
                ('timezone', models.CharField(choices=[('Asia/Tokyo', '日本標準時 (JST)'), ('Australia/Sydney', 'オーストラリア東部標準時 (AEST) - シドニー'), ('Australia/Melbourne', 'オーストラリア東部標準時 (AEST) - メルボルン'), ('Australia/Brisbane', 'オーストラリア東部標準時 (AEST) - ブリスベン'), ('Australia/Perth', 'オーストラリア西部標準時 (AWST) - パース'), ('Australia/Adelaide', 'オーストラリア中部標準時 (ACST) - アデレード')], default='Asia/Tokyo', max_length=50, verbose_name='タイムゾーン')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, core.models.mixins.SecurityMixin, core.models.mixins.TenantAccessMixin, core.models.mixins.PermissionMixin),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('legal_name', models.CharField(blank=True, help_text='正式な法人名', max_length=200, verbose_name='法人名')),
                ('abn', models.CharField(blank=True, help_text='オーストラリア事業者番号', max_length=11, verbose_name='ABN')),
                ('head_office_address', models.TextField(blank=True, verbose_name='本社住所')),
                ('head_office_phone', models.CharField(blank=True, max_length=20, verbose_name='本社電話番号')),
                ('head_office_email', models.EmailField(blank=True, max_length=254, verbose_name='本社メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='AustralianTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CASUAL', 'Casual'), ('CONTRACT', 'Contract')], max_length=20, verbose_name='雇用形態')),
                ('taxfile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Taxfile Number')),
                ('super_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Super Number')),
                ('latest_tax_withheld', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latest Tax Withheld')),
                ('latest_super_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latest Super Amount')),
                ('ytd_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=9, null=True, verbose_name='YTD Tax')),
                ('ytd_super', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=20, null=True, verbose_name='YTD Super')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='last Sync')),
                ('user', models.OneToOneField(limit_choices_to={'country': 'AU'}, on_delete=django.db.models.deletion.CASCADE, related_name='australian_tax_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JapaneseTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_number', models.CharField(blank=True, help_text='12桁の個人番号', max_length=12, verbose_name='マイナンバー')),
                ('pension_number', models.CharField(blank=True, help_text='例: 1234-567890', max_length=20, verbose_name='基礎年金番号')),
                ('employment_insurance_number', models.CharField(blank=True, max_length=20, verbose_name='雇用保険被保険者番号')),
                ('user', models.OneToOneField(limit_choices_to={'country': 'JP'}, on_delete=django.db.models.deletion.CASCADE, related_name='japanese_tax_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='姓')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='User Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'owner_profiles',
                'verbose_name_plural': 'owner_profiles',
                'db_table': 'owner_profiles',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='権限コード')),
                ('name', models.CharField(max_length=100, verbose_name='権限名')),
                ('category', models.CharField(choices=[('reservation', '予約管理'), ('pos', 'POS/販売'), ('inventory', '在庫管理'), ('staff', 'スタッフ管理'), ('customer', '顧客管理'), ('report', 'レポート'), ('settings', '設定')], max_length=50, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['category', 'code'], name='permissions_categor_54d537_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='姓')),
                ('address', models.CharField(max_length=50, verbose_name='住所')),
                ('suburb', models.CharField(blank=True, max_length=100, verbose_name='Suburb/市区町村')),
                ('state', models.CharField(max_length=50, verbose_name='州/都道府県')),
                ('post_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, verbose_name='国')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='入社日')),
                ('unemplyed', models.DateField(blank=True, null=True, verbose_name='Unemplyed')),
                ('is_active', models.BooleanField(default=True, verbose_name='在籍中')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スタッフプロファイル',
                'verbose_name_plural': 'スタッフプロファイル',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='店舗名')),
                ('code', models.CharField(help_text='例: SBY001, MEL002', max_length=50, unique=True, verbose_name='店舗コード')),
                ('address', models.TextField(verbose_name='住所')),
                ('suburb', models.CharField(blank=True, max_length=100, verbose_name='Suburb/市区町村')),
                ('state', models.CharField(max_length=50, verbose_name='州/都道府県')),
                ('post_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, verbose_name='国')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.company', verbose_name='companies')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['company', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='権限コード')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Role / ロール',
                'verbose_name_plural': 'Roles / ロール',
                'db_table': 'roles',
                'ordering': ['tenant', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='店舗に追加された日')),
                ('ended_at', models.DateField(blank=True, help_text='退任・売却日', null=True, verbose_name='店舗終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_menberships', to=settings.AUTH_USER_MODEL, verbose_name='追加者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership / テナント所属',
                'verbose_name_plural': 'Tenant Memberships / テナント所属',
                'db_table': 'tenant_memberships',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効開始日時')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有効終了日時')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='付与日時')),
                ('reason', models.TextField(blank=True, verbose_name='付与理由')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='付与者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='CompanyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='開始日')),
                ('ended_at', models.DateField(blank=True, help_text='退任・売却日', null=True, verbose_name='終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='追加者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='core.company')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Ownership',
                'verbose_name_plural': 'Company Ownerships',
                'db_table': 'company_ownerships',
                'indexes': [models.Index(fields=['company', 'is_active'], name='company_own_company_0a5d26_idx'), models.Index(fields=['owner', 'is_active'], name='company_own_owner_i_8e5a44_idx')],
                'unique_together': {('company', 'owner', 'started_at')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='付与日時')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='付与者')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company', 'is_active'], name='tenants_company_50b1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['code'], name='tenants_code_fcfd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active'], name='roles_tenant__0ca5a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='tenant_memb_user_id_489eee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_memb_tenant__c6bbaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'valid_from', 'valid_until'], name='user_roles_user_id_ed6843_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
