# Generated by Django 5.0 on 2025-11-01 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownerprofile',
            options={'verbose_name': 'オーナープロファイル', 'verbose_name_plural': 'オーナープロファイル'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='unemplyed',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='unemployed_date',
            field=models.DateField(blank=True, null=True, verbose_name='退職日'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, null=True, verbose_name='国'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'user_type'], name='users_email_e7d39f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'user_type'], name='users_is_acti_e1f8d6_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
