# Generated by Django 5.0 on 2025-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_staffregistrationprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apple_user_id',
            new_name='facebook_user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='line_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Apple User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'メール'), ('google', 'Google'), ('line', 'Line'), ('facebook', 'Facebook')], default='email', max_length=20, verbose_name='認証プロバイダー'),
        ),
    ]
