# Generated by Django 5.0 on 2025-11-01 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ownerprofile_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Apple User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='Google User ID'),
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='招待トークン')),
                ('email', models.EmailField(max_length=254, verbose_name='招待メールアドレス')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='姓')),
                ('language', models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='en', max_length=10, verbose_name='言語')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, verbose_name='国')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('invited_by', models.ForeignKey(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='core.tenant')),
            ],
            options={
                'verbose_name': 'スタッフ招待',
                'verbose_name_plural': 'スタッフ招待',
                'db_table': 'staff_invitations',
                'indexes': [models.Index(fields=['token', 'is_used'], name='staff_invit_token_b531f8_idx'), models.Index(fields=['email', 'is_used'], name='staff_invit_email_c3d01e_idx')],
            },
        ),
    ]
