# Generated by Django 5.0 on 2025-11-13 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_apple_user_id_user_facebook_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistrationProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('basic_info', '基本情報'), ('datail', '詳細'), ('done', '完了')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
