# Generated by Django 5.0 on 2025-11-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customerregistrationprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerregistrationprogress',
            name='step',
            field=models.CharField(choices=[('basic_info', '基本情報'), ('detail', '詳細'), ('done', '完了')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='ソーシャルログインの画像URL', null=True, verbose_name='プロフィール画像URL'),
        ),
    ]
