# Generated by Django 5.0 on 2025-11-15 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('legal_name', models.CharField(blank=True, help_text='正式な法人名', max_length=200, verbose_name='法人名')),
                ('abn', models.CharField(blank=True, help_text='オーストラリア事業者番号', max_length=11, verbose_name='ABN')),
                ('head_office_address', models.TextField(blank=True, verbose_name='本社住所')),
                ('head_office_phone', models.CharField(blank=True, max_length=20, verbose_name='本社電話番号')),
                ('head_office_email', models.EmailField(blank=True, max_length=254, verbose_name='本社メールアドレス')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='店舗名')),
                ('code', models.CharField(help_text='例: SBY001, MEL002', max_length=50, unique=True, verbose_name='店舗コード')),
                ('address', models.TextField(verbose_name='住所')),
                ('suburb', models.CharField(blank=True, max_length=100, verbose_name='Suburb/市区町村')),
                ('state', models.CharField(max_length=50, verbose_name='州/都道府県')),
                ('post_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, verbose_name='国')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='organizations.company', verbose_name='companies')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['company', 'code'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='tenants_company_50b1bc_idx'), models.Index(fields=['code'], name='tenants_code_fcfd1b_idx')],
            },
        ),
    ]
