# Generated by Django 5.0 on 2025-11-15 17:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='権限コード')),
                ('name', models.CharField(max_length=100, verbose_name='権限名')),
                ('category', models.CharField(choices=[('reservation', '予約管理'), ('pos', 'POS/販売'), ('inventory', '在庫管理'), ('staff', 'スタッフ管理'), ('customer', '顧客管理'), ('report', 'レポート'), ('settings', '設定')], max_length=50, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['category', 'code'],
                'indexes': [models.Index(fields=['category', 'code'], name='permissions_categor_54d537_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='権限コード')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.tenant', verbose_name='tenant')),
            ],
            options={
                'verbose_name': 'Role / ロール',
                'verbose_name_plural': 'Roles / ロール',
                'db_table': 'roles',
                'ordering': ['tenant', '-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='付与日時')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='付与者')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='permissions.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.role')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='店舗スタート日')),
                ('ended_at', models.DateField(blank=True, help_text='退任・売却日', null=True, verbose_name='店舗終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_menberships', to=settings.AUTH_USER_MODEL, verbose_name='追加者')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.tenant')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'STAFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership / テナント所属',
                'verbose_name_plural': 'Tenant Memberships / テナント所属',
                'db_table': 'tenant_memberships',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='有効開始日時')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有効終了日時')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='付与日時')),
                ('reason', models.TextField(blank=True, verbose_name='付与理由')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL, verbose_name='付与者')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='permissions.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.CreateModel(
            name='CompanyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='開始日')),
                ('ended_at', models.DateField(blank=True, help_text='退任・売却日', null=True, verbose_name='終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='追加者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='organizations.company')),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_ownerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Ownership',
                'verbose_name_plural': 'Company Ownerships',
                'db_table': 'company_ownerships',
                'indexes': [models.Index(fields=['company', 'is_active'], name='company_own_company_0a5d26_idx'), models.Index(fields=['owner', 'is_active'], name='company_own_owner_i_8e5a44_idx')],
                'unique_together': {('company', 'owner', 'started_at')},
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active'], name='roles_tenant__0ca5a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['user', 'is_active'], name='tenant_memb_user_id_489eee_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantmembership',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_memb_tenant__c6bbaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'valid_from', 'valid_until'], name='user_roles_user_id_ed6843_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
