# Generated by Django 5.0 on 2025-11-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=20)),
                ('verification_token', models.CharField(max_length=255, unique=True)),
                ('token_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_pending_user',
                'indexes': [models.Index(fields=['token_expires_at'], name='idx_pending_token_expires'), models.Index(fields=['email', 'user_type'], name='idx_email_pending_user_type')],
            },
        ),
        migrations.AddConstraint(
            model_name='pendinguser',
            constraint=models.UniqueConstraint(fields=('email', 'user_type'), name='unique_email_user_type'),
        ),
    ]
