# Generated by Django 5.0 on 2025-11-17 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='country',
            field=models.CharField(blank=True, choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='タイムゾーン'),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
