# Generated by Django 5.0 on 2025-11-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pendinguser_country_pendinguser_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'オーナー'), ('CUSTOMER', '顧客')], max_length=20),
        ),
    ]
