# Generated by Django 5.0 on 2025-11-18 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_pendinguser_first_name_pendinguser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='timezone',
            new_name='user_timezone',
        ),
    ]
