# Generated by Django 5.0 on 2025-11-15 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='招待トークン')),
                ('email', models.EmailField(max_length=254, verbose_name='招待メールアドレス')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='名')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='姓')),
                ('language', models.CharField(choices=[('ja', '日本語'), ('en', 'English')], default='en', max_length=10, verbose_name='言語')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('JP', 'Japan')], max_length=2, verbose_name='国')),
                ('timezone', models.CharField(choices=[('Asia/Tokyo', '日本標準時 (JST)'), ('Australia/Sydney', 'オーストラリア東部標準時 (AEST) - シドニー'), ('Australia/Melbourne', 'オーストラリア東部標準時 (AEST) - メルボルン'), ('Australia/Brisbane', 'オーストラリア東部標準時 (AEST) - ブリスベン'), ('Australia/Perth', 'オーストラリア西部標準時 (AWST) - パース'), ('Australia/Adelaide', 'オーストラリア中部標準時 (ACST) - アデレード')], max_length=30, verbose_name='Timezone')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用日時')),
                ('invited_by', models.ForeignKey(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_invitations', to='organizations.tenant')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'スタッフ招待',
                'verbose_name_plural': 'スタッフ招待',
                'db_table': 'staff_invitations',
                'indexes': [models.Index(fields=['token', 'is_used'], name='staff_invit_token_b531f8_idx'), models.Index(fields=['email', 'is_used'], name='staff_invit_email_c3d01e_idx')],
            },
        ),
    ]
